site_name: oneflow-yolo-doc
use_directory_urls: false

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
    - 首页🏠: index.md

    - YOLOv5教程📚:
        -  1. one-yolov5 特点解析: tutorials/00_chapter/overview.md
        -  2. YOLOv5 网络结构解析: tutorials/01_chapter/yolov5_network_structure_analysis.md
        -  3. 如何准备YOLOv5模型训练数据: tutorials/02_chapter/how_to_prepare_yolov5_training_data.md
        -  4. 快速开始: tutorials/03_chapter/quick_start.md
        -  5. 模型训练: tutorials/03_chapter/model_train.md
        -  6. 测试时增强 (TTA): tutorials/03_chapter/TTA.md
        -  7. 模型融合 (Model Ensembling): tutorials/03_chapter/model_ensembling.md
        -  8. 从 OneFlow Hub 加载 YOLOv5: tutorials/03_chapter/loading_model_from_oneflowhub.md
        -  9. 数据增强: tutorials/04_chapter/mosaic.md
        -  10. 矩形推理: tutorials/05_chapter/rectangular_reasoning.md
        -  11. IOU深入解析: tutorials/05_chapter/iou_in-depth_analysis.md
        -  12. 模型精确度评估: tutorials/05_chapter/map_analysis.md
        -  13. 模型导出: tutorials/06_chapter/export_onnx_tflite_tensorrt.md
        -  14. 计算mAP用到的numpy函数: tutorials/05_chapter/Introduction_to_functions_used_in_metrics.md
    
    - 论文解读:
        - history: thesis_interpretation/00_yolo_history.md
        - YOLOv1 : thesis_interpretation/01_yolo.md
        - YOLOv2 : thesis_interpretation/02_yolo.md
        - YOLOv3 : thesis_interpretation/03_yolo.md
        - YOLOv4 : thesis_interpretation/04_yolo.md
        - YOLOv6 : thesis_interpretation/06_yolo.md
